version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=dev"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - open
    volumes:
      - nginx:/etc/nginx:rw

  dockergen:
    image: jwilder/docker-gen:latest
    command: -notify-sighup ${COMPOSE_PROJECT_NAME}_nginx_1 -watch /etc/nginx/conf.d/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - open
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx:/etc/nginx:rw

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=dev"
    env_file:
      - ${ENV_FILE}
      - ${SECRET_FILE}
    environment:
      - PROXY=transmart
      - PROXY_RULE=^~ /transmart/
      - PROXY_PORT=8080
      # debug options
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
      - CATALINA_OPTS=-Xms512m -Xmx2g -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:PermSize=512m -XX:MaxPermSize=512m
    entrypoint: ./bin/catalina.sh jpda run
    restart: always
    depends_on:
      - nginx
    networks:
      - open
    expose:
      - 8080
    ports:
      - 8080:8080
      # debug port
      - 8000:8000
    volumes:
      - rserve-jobs:/tmp:rw
      # local transmart.war directory (for simple development)
      - ${LOCAL_TRANSMART:-transmart}:/usr/local/tomcat/webapps/

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=dev"
    restart: always
    networks:
      - open
    expose:
      - 6311
    ports:
      - 6311:6311
    volumes:
      - rserve-jobs:/tmp:rw


  # solr
  solr:
    image: dbmi/solr:${solr_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=dev"
    env_file:
      - ${ENV_FILE}
      - ${SECRET_FILE}
    environment:
      - PROXY=solr
      - PROXY_PORT=8983
      - PROXY_PATH=/solr
      # debug options
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=1044,server=y,suspend=y"
      - JPDA_ADDRESS=1044
      - JPDA_TRANSPORT=dt_socket
    restart: always
    networks:
      - open
    ports:
      - 8983:8983
      # debug port
      - 1044:1044
    expose:
      - 8983

volumes:
  # shared volume for nginx templates
  nginx:
  # shared volume for R jobs
  rserve-jobs:
  # default development transmart volume
  transmart:

networks:
    open:
