version: '3.3'
services:

    etl:
        image: dbmi/transmart-etl:${etl_version}
        env_file:
            - ${ENV_FILE}
        environment:
            # Kettle ETL bug
            - DB_ORASID=${DB_ORASVC}
        depends_on:
            - db
        networks:
            - public

    schema:
        image: dbmi/transmart-data:${schema_version}
        env_file:
            - ${ENV_FILE}
        depends_on:
            - db
        networks:
            - public

    db:
        image: dbmi/${db_type}:${db_version}
        env_file:
            - ${ENV_FILE}
        networks:
            # public network used to access DB from outside (e.g. SQLDeveloper)
            - public
        volumes:
            # TODO: eventually remove this as a volume and add it
            # to the dbmi/oracle base image -Andre
            - ./startup:/opt/oracle/scripts/startup:ro
        expose:
            - 1521
        ports:
            - 1521:1521



networks:
    public:
