version: '3.3'
services:
    nginx:
        image: dbmi/nginx:${nginx_version}
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - public

    transmart:
        image: dbmi/transmart:${transmart_version}
        restart: always
        depends_on:
            - db
        networks:
            - public
        expose:
            - 8080
        volumes:
         - rserve-jobs:/var/tmp:rw

    gwava:
        image: dbmi/gwava:${gwava_version}
        restart: always
        networks:
            - public
        expose:
            - 8080

    rserve:
        image: dbmi/rserve:${rserve_version}
        restart: always
        networks:
            - public
        expose:
            - 6311
        volumes:
            - rserve-jobs:/var/tmp:rw

    solr:
        image: dbmi/solr:${solr_version}
        restart: always
        networks:
            - public
        expose:
            - 8983

    db:
        image: dbmi/transmart-db:${db_version}
        networks:
            - public
        expose:
            - 1521
        ports:
            - 1521:1521


volumes:
  # shared volume for R jobs
  rserve-jobs:

networks:
    public:
