version: '3.3'
services:
    nginx:
        image: dbmi/nginx:${nginx_version}
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - public
            - private

    transmart:
        image: dbmi/transmart:${transmart_version}
        restart: always
        networks:
            - private
        expose:
            - 8080

    gwava:
        image: dbmi/gwava:${gwava_version}
        restart: always
        networks:
            - private
        expose:
            - 8080

    rserve:
        image: dbmi/rserve:${rserve_version}
        restart: always
        networks:
            - private
        expose:
            - 6311

    solr:
        image: dbmi/solr:${solr_version}
        restart: always
        networks:
            - private
        expose:
            - 8983

    db:
        image: dbmi/transmart-db:${db_version}
        networks:
            - private
        expose:
            - 1521



networks:
    private:
        # encrypted network
        internal: true
    public:
