version: '3.3'
services:

  i2b2-db:
    image: dbmi/${i2b2_db_type:-i2b2transmart}-db:${i2b2_db_version:-oracle.12.2.0.1-ee-i2b2.1.7.09-tm.release-18.1-v.1.3}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - closed
    expose:
      - 1521


networks:
    # these are expected to have already by created by
    # either ../dev.yml or ../prod.yml
   closed:
       external:
           name: ${COMPOSE_PROJECT_NAME}_closed
