version: '3.3'
services:

  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:${irct_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
      - ${SECRET_FILE}
    restart: always
    networks:
      - closed
    expose:
      - 8080

  irct-init:
    image: dbmi/irct-init:${irct_init_version}
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
      - ${SECRET_FILE}
    networks:
      - closed

  # IRCT DB
  db:
    image: mysql:${mysql_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
      - ${SECRET_FILE}
    environment:
      - MYSQL_DATABASE=irct
    command: --datadir=/mysql/data
    restart: always
    expose:
      - 3306
    networks:
      - closed

networks:
    # no outbound access available on closed network
    # only inter-container communication available
    # encrypted network
    closed:
        driver: overlay
        internal: true
        driver_opts:
            encrypted: "true"
        attachable: true
