version: '3.3'
services:

  # nginx
  nginx:
    image: nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - public
      - private
    volumes:
      - nginx:/etc/nginx/conf.d/:rw

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - private
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx:/etc/nginx/conf.d/:rw
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:rw

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - nginx
    environment:
      - VIRTUAL_HOST=transmart
    networks:
      - private
    expose:
      - 8080

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - private
    expose:
      - 6311

  # solr
  solr:
    image: dbmi/solr:${solr_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - private
    expose:
      - 8983

  db:
    image: dbmi/i2b2transmart-db:${db_version:-oracle.12.2.0.1-ee-i2b2.1.7.09-tm.release-18.1-v.1.0}
    networks:
      - private
    expose:
      - 1521

volumes:
    nginx:

networks:
    public:
    private:
        internal: true
